export const ogItems = [
    {"quantity":3,"title":"Hovis Tasty Wholemeal Medium Bread","price":99},
    {"quantity":1,"title":"Morrisons Brown Onions","price":75},
    {"quantity":1,"title":"Morrisons Red Onions","price":100},
    {"quantity":2,"title":"Morrisons Long Life British Whole Milk","price":450},
    {"quantity":4,"title":"Morrisons White With More Wraps","price":100},
    {"quantity":5,"title":"7 Moon Udon Noodles","price":80},
    {"quantity":2,"title":"Frenchs American Classic Mustard","price":185},
    {"quantity":1,"title":"Healthy Boy Brand Thin Soy Sauce","price":220},
    {"quantity":1,"title":"Hellmann's Real Squeezy Mayonnaise","price":300},
    {"quantity":1,"title":"Kellogg's Crunchy Nut","price":300},
    {"quantity":6,"title":"KTC Chick Peas (400g)","price":35},
    {"quantity":8,"title":"KTC Chopped Tomatoes","price":35},
    {"quantity":1,"title":"KTC Red Kidney Beans","price":200},
    {"quantity":2,"title":"Milka Yoghurt 100% Alpine Milk Chocolate","price":100},
    {"quantity":1,"title":"Morrisons Baked Beans","price":100},
    {"quantity":1,"title":"Morrisons Blackcurrant Jam","price":65},
    {"quantity":2,"title":"Morrisons Cornflour","price":75},
    {"quantity":2,"title":"Morrisons Desiccated Coconut","price":130},
    {"quantity":1,"title":"Morrisons Easy Cook Brown Long Grain Rice","price":185},
    {"quantity":1,"title":"Morrisons Ground Black Pepper","price":75},
    {"quantity":3,"title":"Morrisons Jumbo Salted Peanuts","price":100},
    {"quantity":2,"title":"Morrisons Penne","price":50},
    {"quantity":1,"title":"Morrisons Plain Flour","price":80},
    {"quantity":2,"title":"Morrisons Raspberry Jam","price":65},
    {"quantity":1,"title":"Morrisons Red Wine Vinegar","price":80},
    {"quantity":4,"title":"Morrisons Sardines In Brine (120g)","price":40},
    {"quantity":1,"title":"Morrisons Savers Porridge Oats","price":75},
    {"quantity":1,"title":"Morrisons Sesame Seeds","price":85},
    {"quantity":2,"title":"Morrisons Strawberry Jam","price":65},
    {"quantity":4,"title":"Morrisons Sweetcorn In Water","price":70},
    {"quantity":1,"title":"Morrisons Tomato Puree","price":40},
    {"quantity":1,"title":"Morrisons White Wine Vinegar","price":80},
    {"quantity":1,"title":"Mother Africa Peanut Butter","price":180},
    {"quantity":1,"title":"M savers Ground Black Pepper","price":40},
    {"quantity":10,"title":"M savers Milk Chocolate","price":30},
    {"quantity":1,"title":"Sacla' Classic Basil Pesto","price":200},
    {"quantity":1,"title":"Salaam Basmati Rice","price":1100},
    {"quantity":2,"title":"Morrisons Original Source","price":135},
    {"quantity":1,"title":"Cushelle Quilted 9 White Rolls","price":500},
    {"quantity":1,"title":"Morrisons Shea Butter Toilet Tissue 9 Roll","price":350},
    {"quantity":1,"title":"Lynx Excite Body Spray Deodorant For Men","price":200},
    {"quantity":3,"title":"Radox Moisturise Shower Cream","price":90},
    {"quantity":1,"title":"Morrisons Black Pudding Slices","price":100},
    {"quantity":6,"title":"Morrisons British Minced Beef 20% Fat","price":160},
    {"quantity":1,"title":"Morrisons Smoked Back Bacon 20 Rashers","price":350},
    {"quantity":1,"title":"Morrisons Carrots","price":30},
    {"quantity":1,"title":"Morrisons Fresh Chives","price":70},
    {"quantity":1,"title":"Morrisons Iceberg Lettuce","price":70},
    {"quantity":1,"title":"Morrisons Kiwi","price":85},
    {"quantity":1,"title":"Morrisons Market Street Large Cucumber","price":85},
    {"quantity":1,"title":"Morrisons Round Lettuce","price":65},
    {"quantity":2,"title":"Morrisons Salad Onions (minimum 100g)","price":50},
    {"quantity":2,"title":"Morrisons Salad Peppers","price":125},
    {"quantity":1,"title":"Morrisons Sweet Potatoes","price":100},
    {"quantity":1,"title":"Morrisons Tangerines","price":160},
    {"quantity":1,"title":"Morrisons White Potatoes","price":150},
    {"quantity":1,"title":"Arctic Blast Cold Brew Coffee Protein Shot","price":150},
    {"quantity":1,"title":"Clover Spread","price":335},
    {"quantity":2,"title":"Morrisons Carvery Turkey","price":175},
    {"quantity":1,"title":"Morrisons Chocolate Flavoured Fresh Milk","price":100},
    {"quantity":5,"title":"Morrisons Danish Salami","price":110},
    {"quantity":2,"title":"Morrisons Double Cream","price":110},
    {"quantity":8,"title":"Morrisons Free Range Eggs Large","price":90},
    {"quantity":5,"title":"Morrisons German Pepperoni","price":120},
    {"quantity":5,"title":"Morrisons German Salami","price":120},
    {"quantity":4,"title":"Morrisons Greek Style Honey Yogurt","price":55},
    {"quantity":2,"title":"Morrisons Italian Mascarpone","price":165},
    {"quantity":4,"title":"Morrisons Mild Cheddar","price":200},
    {"quantity":1,"title":"Morrisons Wafer Thin Smoked Ham Slices","price":200},
    {"quantity":1,"title":"Morrisons White Chocolate Flavoured Fresh Milk","price":100},
    {"quantity":8,"title":"Piatnica Soured Cream","price":135},
    {"quantity":2,"title":"Morrisons The Best Large Vine Tomatoes","price":150},
    {"quantity":2,"title":"Morrisons Greek Style Yogurt with Honey","price":90},
    {"quantity":1,"title":"Countrystyle 6 Jam & Cream Doughnuts","price":100},
    {"quantity":1,"title":"Morrisons British Garden Peas","price":200},
    {"quantity":2,"title":"Morrisons Double Chocolate Ice Cream Sundae","price":150},
    {"quantity":1,"title":"Morrisons Fine Whole Green Beans","price":100},
    {"quantity":1,"title":"Morrisons Neapolitan Ice Cream","price":165}
];

export const ogDelivery = {
    price: 460,
    date: "2020-02-23"
};

export const ogPayers = [
    {id: 1, name: "Kriszcson"},
    {id: 2, name: "Snajder"},
    {id: 3, name: "Szabo"},
];

export const testData = {
    delivery: ogDelivery,
    items: ogItems,
    payers: ogPayers,
}